[package]
name = "web-service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-files = "0.6.6"
tokio = { version = "1", features = ["full"] }
env_logger = "0.9"
serde = { version="1.0.210", features = ["derive"] }
comms = { path = "../comms" }
